version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "next"
        versions: ["17.*", "18.*"] # Evitamos actualizaciones mayores automáticas que rompan el código

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
